### ISSUE TITLE
How to use it with ssh?

### ISSUE THREAD

**Issue by bhargav3** [BWITS/docker-git-alpine#1]
I'm using this image for rancherOS and would like to use ssh for automated deployments but seems like I can't use ssh with this image. Here is the error I see when I try to `git clone`,

`Cloning into 'foo'...`
`error: cannot run ssh: No such file or directory`
`fatal: unable to fork`

**Comment by SydOps** [comment]
I have updated the image with openssh package installed, could you pull and try again?

**Comment by bhargav3** [comment]
Thanks for the update. I have updated your image to latest and tried to clone the repo again, I see a different error.

```
Cloning into 'foo'...
The authenticity of host 'bitbucket.org (104.192.143.1)' can't be established.
RSA key fingerprint is SHA256:zzXQOXSRBEiUtuE8AikJYKwbHaxvSc0ojez9YXaGp1A.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'bitbucket.org,104.192.143.1' (RSA) to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

How do I make the image use `.ssh` directory of the user running that image?
